### ISSUE TITLE
在sandboxie中启动的任何应用都无法输入中文

### ISSUE THREAD

**Issue by heinulix** [rime/weasel#656] opened 2021-08-05 01:05 UTC
系统为Win10ltsc ,weasel版本为最新版0.14.3
<img width="330" alt="cpture_2021-08-05_09-05-07" src="https://user-images.githubusercontent.com/87571511/128275075-ed5b0982-2ecd-48f8-b531-87d43e21e63a.png">

**Comment by xyqyear** [comment] 2021-10-31 12:41
在沙盒资源访问设置中添加允许访问 "\Device\NamedPipe\xyqye\WeaselNamedPipe"
![image](https://user-images.githubusercontent.com/29950788/139583689-d5b2e5c4-14f2-4eae-bd52-710b719a9436.png)

**Comment by Prcuvu** [comment] 2021-11-25 06:55
Duplicate of #143

**Closed by Prcuvu** 2021-11-25 06:55 UTC
Labels: duplicate
