### ISSUE TITLE
【小狼毫】复刻了一下win11新输入法风格的皮肤，希望支持候选框圆角

### ISSUE THREAD

**Issue by cdc94** [rime/weasel#747] opened 2022-07-25 15:19 UTC
![图片](https://user-images.githubusercontent.com/48703668/180814276-d6565120-f118-495c-b407-132fddb252a6.png)
weasel.custom.yaml

patch:
  "style/color_scheme": win11
  "style/horizontal": true
  "style/inline_preedit": true
  style/display_tray_icon: true
  "style/font_face": "Microsoft YaHei UI"
  "style/font_point": 13
  "style/layout/border_width": 0
  "style/layout/border": 0
  "style/layout/margin_x": 8
  "style/layout/margin_y": 8
  "style/layout/hilite_padding": 1
  "style/layout/hilite_spacing": 16
  "style/layout/candidate_spacing": 24
  "style/layout/round_corner": 9
  "corner_radius": 5
  "style/color_scheme": cdc
  "preset_color_schemes/cdc":
    name: cdc94/cdc
    author: cdc
    text_color: 0xffffff
    back_color: 0x2c2c2c
    border_color: 0x000000
    hilited_text_color: 0xdec4b0
    hilited_candidate_text_color: 0xffffff
    hilited_candidate_back_color: 0xed9564

**Comment by fxliang** [comment] 2022-08-01 03:58
收集一点反馈
[链接](https://github.com/fxliang/weasel/releases)

![image](https://user-images.githubusercontent.com/4023160/182069076-fc689156-8899-4ffa-b0c0-b37ee366a390.png)

```yaml
patch:
  style/color_font: true
  style/font_face: "Segoe UI, Segoe UI Emoji:1f000:1f09f, Noto Color Emoji SVG:80, Microsoft Yahei, 全宋体-1, 全宋体-2, 全宋体-3, 全宋体-F, 全宋体-X, 全宋体(调和), 全宋体(等宽)"
  style/label_font_face: "Segoe UI, Noto Color Emoji SVG:80 , Microsoft Yahei"
  style/font_point: 20
  style/label_font_point: 20
  style/comment_font_point: 12
  style/color_scheme: lost_temple
  style/horizontal: false
  style/inline_preedit: true
  style/layout/border: 2
  style/layout/spacing: 20
  style/layout/candidate_spacing: 10
  style/layout/shadow_radius:   3 
  style/layout/shadow_offset_x: 3
  style/layout/shadow_offset_y: 3
  style/layout/hilite_padding:  6
  style/layout/hilite_spacing: 10
  style/layout/margin_x: 20
  style/layout/margin_y: 20
  style/layout/round_corner:   5
  style/layout/corner_radius: 10

  # color_schemes customization
  preset_color_schemes/lost_temple/hilited_candidate_shadow_color: 0x90000000
  preset_color_schemes/lost_temple/candidate_shadow_color: 0x00000000
  preset_color_schemes/lost_temple/candidate_back_color: 0x00666666
  preset_color_schemes/lost_temple/hilited_shadow_color: 0x60000000
  preset_color_schemes/lost_temple/shadow_color: 0x90000000
```

**Comment by ssxwcz** [comment] 2022-08-02 07:16
> 

你这个要怎么安装，我解压下来的程序包直接使用setup这个程序后右键无法打开设置界面，使用rime-install.bat脚本又报错了
![image](https://user-images.githubusercontent.com/43665491/182314957-41e2b1bd-50e1-4f12-b28d-8da823a15402.png)
> 收集一点反馈 [链接](https://github.com/fxliang/weasel/releases)
> 
> ![image](https://user-images.githubusercontent.com/4023160/182069076-fc689156-8899-4ffa-b0c0-b37ee366a390.png)
> 
> ```yaml
> patch:
>   style/color_font: true
>   style/font_face: "Segoe UI, Segoe UI Emoji:1f000:1f09f, Noto Color Emoji SVG:80, Microsoft Yahei, 全宋体-1, 全宋体-2, 全宋体-3, 全宋体-F, 全宋体-X, 全宋体(调和), 全宋体(等宽)"
>   style/label_font_face: "Segoe UI, Noto Color Emoji SVG:80 , Microsoft Yahei"
>   style/font_point: 20
>   style/label_font_point: 20
>   style/comment_font_point: 12
>   style/color_scheme: lost_temple
>   style/horizontal: false
>   style/inline_preedit: true
>   style/layout/border: 2
>   style/layout/spacing: 20
>   style/layout/candidate_spacing: 10
>   style/layout/shadow_radius:   3 
>   style/layout/shadow_offset_x: 3
>   style/layout/shadow_offset_y: 3
>   style/layout/hilite_padding:  6
>   style/layout/hilite_spacing: 10
>   style/layout/margin_x: 20
>   style/layout/margin_y: 20
>   style/layout/round_corner:   5
>   style/layout/corner_radius: 10
> 
>   # color_schemes customization
>   preset_color_schemes/lost_temple/hilited_candidate_shadow_color: 0x90000000
>   preset_color_schemes/lost_temple/candidate_shadow_color: 0x00000000
>   preset_color_schemes/lost_temple/candidate_back_color: 0x00666666
>   preset_color_schemes/lost_temple/hilited_shadow_color: 0x60000000
>   preset_color_schemes/lost_temple/shadow_color: 0x90000000
> ```

**Comment by Prcuvu** [comment] 2022-08-14 13:22
Duplicate of #745

**Closed by Prcuvu** 2022-08-14 13:22 UTC
Labels: duplicate
